<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cetak Bank Soal</title>
<link rel="stylesheet" href="<?= base_url('assets/vendor/katex/katex.min.css') ?>">
<style>body{font:14px/1.5 Ubuntu,Arial,sans-serif;max-width:900px;margin:24px auto;color:#111}h1{font-size:22px;margin-bottom:0}h2{font-size:16px}.question{page-break-inside:avoid;border-top:1px solid #ddd;padding:15px 0}.answers{color:#234e28;margin:8px 0}.controls{display:flex;gap:8px;align-items:center;margin-bottom:20px}button{padding:8px 12px;cursor:pointer}.table{border-collapse:collapse;max-width:100%;overflow-wrap:anywhere}.table th,.table td{border:1px solid #bbb;padding:5px}.border{border:1px solid #bbb}.rounded{border-radius:4px}.p-2{padding:8px}.p-3{padding:12px}.mb-3{margin-bottom:12px}.mb-2{margin-bottom:8px}.d-grid{display:grid}.gap-2{gap:8px}.fw-semibold{font-weight:600}.border-start{border-left:3px solid #888}.ps-3{padding-left:12px}.badge{margin-left:8px}.text-success{color:#234e28}.text-secondary{color:#666}.d-block{display:block}.mt-2{margin-top:8px}@media print{body{margin:0;max-width:none}.controls{display:none}.question{break-inside:avoid}@page{size:A4;margin:16mm}}</style></head><body>
<div class="controls"><button type="button" id="printBankButton" disabled>Cetak / Simpan PDF</button><label><input type="checkbox" id="printBankAnswer"> Sertakan kunci dan rubrik</label><a href="<?= base_url('manager/master-ujian/bank-soal') ?>">Kembali</a></div>
<h1 id="printBankTitle">Memuat Bank Soal...</h1><p id="printBankContext"></p><div id="printBankQuestions"></div>
<script src="<?= base_url('assets/vendor/katex/katex.min.js') ?>"></script>
<script src="<?= base_url('assets/js/question-renderer.js') ?>"></script>
<script>window.bankPrintApi = <?= json_encode(base_url('manager/api/bank-soal/' . $bankId . '/soal'), JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT) ?>;</script>
<script src="<?= base_url('assets/js/manager-bank-print.js') ?>"></script></body></html>
